web:
  name: firsflaskronunningonk8s
  app: firsflaskronunningonk8s
  image: new_flask_app_version2
  replicas: 3
  imagePullPolicy: Never
  containerPort: 5000

service:
  name: flaskwebservice
  port: 5000
  protocol: TCP
  targetPort: 5000
  app: firsflaskronunningonk8s
  type: NodePort

