web:
  name: firsflaskronunningonk8s
  app: firsflaskronunningonk8s
  image: public.ecr.aws/f7j1n6h0/sravan-py-flask-webserver
  replicas: 4
  imagePullPolicy: Always
  containerPort: 5000

service:
  name: flaskwebservice
  port: 5000
  protocol: TCP
  targetPort: 5000
  app: firsflaskronunningonk8s
  type: NodePort

